# -----------------------------------------------
# Copy docker config files and dbs to server
# -----------------------------------------------
- name: Get a list of all running containers
  community.docker.docker_host_info:
    containers: true
    containers_all: true
    verbose_output: true
  register: result

- name: Stop all running containers
  become: true
  shell:
    cmd: "docker-compose -f docker-compose.yml down"
    chdir: /server/docker-compose/{{ item.Names[0] | regex_replace("^/", "") }}
  loop: '{{ result.containers }}'

- name: Backup docker configs and dbs to server
  copy:
    remote_src: true
    src: /server/containers
    dest: /backups/