# main.yml
---
- name: Mount the Unraid Docker Volume Share
  hosts: docker_host
  become: true
  vars:
    samba_server: "192.168.1.100"
    samba_share: "vm-docker-data"
    samba_username: "nobody"
    samba_password: "none"
    samba_mount_user: "root"
    samba_mount_group: "root"
  tasks:
    - name: Update System
      include_role:
        name: apt-upgrade

    - name: Mount SMB File Share
      include_role:
        name: samba_mount

    - name: Install Docker System
      include_role:
        name: docker_install

    - name: Start Docker System Services
      include_role:
        name: docker_system_services
