---
- name: Onboard PVE Nodes
  hosts: pvenodes

  vars:
    ansible_user: root

  tasks:

    # - name: Display the remote user
    #   debug:
    #     msg: "The remote user is {{ ansible_user }}"

    - name: Install sudo package
      ansible.builtin.apt:
        name:
          - sudo=1.9.13p3-1deb12u1
          - python3-proxmoxer=1.2.0-2
          - libguestfs-tools=1:1.48.6-2
        state: present
        update_cache: true
        cache_valid_time: 3600
        # only_upgrade: true # <- Upgrades but does not install additional packages.

    - name: Create user ansible
      ansible.builtin.user:
        name: ansible
        shell: '/bin/bash'

    - name: Add Ansible ssh key
      ansible.posix.authorized_key:
        user: ansible
        key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIHjV3zGbywSODoUt2Rn+W4qe25LLvn644lvkI8ggY/f ansible@footeprint.lan

    - name: Add ansible user to sudoers
      ansible.builtin.copy:
        src: sudoer_ansible
        dest: /etc/sudoers.d/ansible
        owner: root
        group: root
        mode: "0440"
        force: false
