---
- name: Install required Ansible collections
  hosts: localhost
  tasks:
    - name: Ensure community.general collection is installed
      ansible.builtin.command:
        cmd: ansible-galaxy collection install community.general

    - name: Ensure TrueNAS Scale collection is installed (if available)
      ansible.builtin.command:
        cmd: ansible-galaxy collection install arensb.truenas
      ignore_errors: yes
