---
- name: Update known_hosts file on the Ansible control node
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Remove old SSH key for each node in windows_nodes
      ansible.builtin.known_hosts:
        path: ~/.ssh/known_hosts
        name: "{{ hostvars[item].ansible_host }}"
        state: absent
      with_items: "{{ groups['windows_nodes'] }}"

    - name: Add new SSH key for each node in windows_nodes
      ansible.builtin.known_hosts:
        path: ~/.ssh/known_hosts
        name: "{{ hostvars[item].ansible_host }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -t ed25519 ' ~ hostvars[item].ansible_host) }}"
        state: present
      with_items: "{{ groups['windows_nodes'] }}"
