---
- name: Set the windows shell to PowerShell
  hosts: windows_nodes
  gather_facts: false

  vars:
    ansible_user: "{{windows_default_user}}"
    ansible_password: "{{windows_default_user_pass}}"

  vars_files:
    - secrets.yml

  tasks:
    # If the system has SSH default to using cmd shell, switch it.
    # If already PowerShell then error out and ignore
    - name: Set the default shell to PowerShell
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\OpenSSH
        name: DefaultShell
        data: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
        type: string
        state: present
      ignore_errors: true
      failed_when: >
        (check_result.changed == false) and (check_result.msg != "MODULE FAILURE\nSee stdout/stderr for the exact error")
      vars:
        ansible_shell_type: cmd
      register: check_result

    # - name: Debug the step
    #   ansible.builtin.debug:
    #     var: test

    # - name: set the default shell to cmd
    #   ansible.windows.win_regedit:
    #     path: HKLM:\SOFTWARE\OpenSSH
    #     name: DefaultShell
    #     state: absent
    #   vars:
    #     ansible_shell_type: powershell

    - name: Reset SSH connection after shell change
      ansible.builtin.meta: reset_connection
      # vars:
      #   ansible_shell_type: cmd

    # - name: Ensure OpenSSH is installed properly installed from internal repo
    #   chocolatey.chocolatey.win_chocolatey:
    #     name: openssh
    #     state: latest
    #     choco_args:
    #       - '-packageParameters="/SSHServerFeature"'

    # - name: Display ansible_facts
    #   debug:
    #     var: hostvars
