---
- name: Create an Ansible user for future use
  hosts: windows_nodes
  gather_facts: false

  vars:
    ansible_user: "{{remote_ansible_user}}"
    ansible_password: "{{ remote_ansible_user_pass }}"
    # ansible_ssh_private_key_file: ~/.ssh/msfoote_key

  vars_files:
    - secrets.yml

  tasks:
    - name: Ensure Chocolatey installed from internal repo
      chocolatey.chocolatey.win_chocolatey:
        name: chocolatey
        state: latest

    - name: Install default tools
      chocolatey.chocolatey.win_chocolatey:
        name:
          - PSWindowsUpdate
          - 7zip
          - wiztree
          - wireguard
          - vcredist-all
          - directx
          - PowerShell
          - dotnet
          - nano
          - ssh-copy-id
          - autoruns
          - sysinternals
          - powertoys
          - git
        state: latest

    - name: Install gaming tools
      chocolatey.chocolatey.win_chocolatey:
        name: '{{ item }}'
        state: latest
      loop:
        - steam
      tags: gaming
      when: "'gaming' in group_names"

    - name: Install test tools
      chocolatey.chocolatey.win_chocolatey:
        name: '{{ item }}'
        state: latest
      loop:
        - rdm
      tags: test
      when: "'test' in group_names"
