all:
  children:
    all_nodes:
      hosts:
        test-pc:
          ansible_host: 192.168.1.180
          # ansible_user: msfoote
          # ansible_ssh_private_key_file: ~/.ssh/msfoote_key
          ansible_connection: ssh
          ansible_shell_type: powershell
        matthew-pc:
          ansible_host: 192.168.1.98 # 89
          # ansible_user: msfoote
          # ansible_ssh_private_key_file: ~/.ssh/msfoote_key
          ansible_connection: ssh
          ansible_shell_type: powershell
          ansible_shell_executable: powershell.exe
        monica:
          ansible_host: 192.168.1.101
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/ansible_key
        rocinante:
          ansible_host: 192.168.1.103
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/ansible_key
        truenas:
          ansible_host: 192.168.1.114
          ansible_user: msfoote
          ansible_ssh_private_key_file: ~/.ssh/msfoote_key
    windows_nodes:
      hosts:
        matthew-pc:
        test-pc:
    gaming:
      hosts:
        matthew-pc:
    development:
      hosts:
        matthew-pc:
        test-pc:
    entertainment:
      hosts:
        matthew-pc:
    test:
      hosts:
        test-pc:

    pvenodes:
      hosts:
        monica:
        rocinante:

    truenasnodes:
      hosts:
        truenas:
