---  # Start with YAML document marker
all:
  children:
    all_nodes:
      hosts:
        matthew-pc:
          ansible_host: 192.168.1.89
          ansible_user: msfoote
          ansible_password: "{{ windows_default_user_pass }}"
          ansible_ssh_private_key_file: ~/.ssh/ansible_key
          ansible_connection: ssh
          ansible_shell_type: powershell
          ansible_shell_executable: powershell.exe
          tags: ['windows', 'gaming', 'development', 'entertainment']
        tyson-pc:
          ansible_host: 192.168.1.88
          ansible_user: msfoote
          ansible_password: "{{ windows_default_user_pass }}"
          ansible_ssh_private_key_file: ~/.ssh/ansible_key
          ansible_connection: ssh
          ansible_shell_type: powershell
          ansible_shell_executable: powershell.exe
          tags: ['windows']
        maxhub:
          ansible_host: 192.168.1.40
          ansible_password: "{{ windows_default_user_pass }}"
          ansible_connection: ssh
          ansible_shell_type: powershell
          ansible_shell_executable: powershell.exe
          tags: ['windows']
        Windows_Scanner:
          ansible_host: 192.168.1.156
          ansible_user: matthew
          ansible_password: "{{ windows_default_user_pass }}"
          ansible_ssh_private_key_file: ~/.ssh/ansible_key
          ansible_connection: ssh
          ansible_shell_type: powershell
          ansible_shell_executable: powershell.exe
          tags: ['windows']
        truenas:
          ansible_host: 192.168.1.114
          ansible_user: msfoote
          ansible_ssh_private_key_file: ~/.ssh/msfoote_key
          tags: ['truenas']
        monica:
          ansible_host: 192.168.1.101
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/ansible_key
          tags: ['pve']
        HP1:
          ansible_host: 192.168.1.110
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/ansible_key
          tags: ['pve']
        HomeAssistant:
          ansible_host: 192.168.1.20
          tags: ['homeassistant']
        dockge:
          ansible_host: 192.168.1.11
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/msfoote_key
          tags: ['docker']
        ansible:
          ansible_host: 192.168.1.116
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/ansible_key
          tags: ['ansible']
        docker_host:
          ansible_host: 192.168.1.39
          ansible_user: msfoote
          ansible_ssh_private_key_file: ~/.ssh/msfoote_key
          tags: ['docker']
        # hp2_docker_host:
        #   ansible_host: 192.168.1.38
        #   ansible_user: msfoote
        #   ansible_ssh_private_key_file: ~/.ssh/msfoote_key
        #   tags: ['docker']
        fatmandu_docker_host:
          ansible_host: 192.168.1.30
          ansible_user: msfoote
          ansible_ssh_private_key_file: ~/.ssh/msfoote_key
          tags: ['docker']

    docker:
      hosts:
        # dockge:
        docker_host:
        # hp2_docker_host:
        # fatmandu_docker_host:
