- hosts: "ubuntu"
  become: yes
- name: Update and Upgrade Packages
  import_playbook: apt.yml
- name: Install and start QEMU Guest Agent
  import_playbook: qemu-guest-agent.yml
- name: Update Timezone
  import_playbook: timezone.yml
- name: Mount Unraid Docker Volume
  import_playbook: mount_unraid_docker_volume.yml