services:
  fenrus:
    image: revenz/fenrus
    container_name: fenrus
    environment:
      - TZ=American/Phoenix
    volumes:
      - /server/containers/fenrus:/app/data
    ports:
      - 3000:3000
    restart: unless-stopped