---
- name: Create a VM
  hosts: monica
  vars_files:
    - /root/ansible/group_vars/secrets.yml
  serial: 1
  tasks:

    # Adapted from https://joshrnoll.com/deploying-proxmox-vms-with-ansible-part-2/

    - name: Create new vm with minimal options
      vars:
        ansible_python_interpreter: /usr/bin/python3
      # community.general.proxmox_kvm:
      community.general.proxmox_kvm:
        api_user: "{{ pve_monica_api_user }}"
        api_token_id: "{{ pve_monica_api_token_id }}"
        api_token_secret: "{{ pve_monica_api_token_secret }}"
        api_host: "{{ pve_monica_api_host }}"
        node: k3s1
        name: Docker_Host
        # clone: ubuntu-cloud
        vmid: 9000
        storage: Speedy
        memory: 4096
        cores: 4
        state: present
      register: result
      #   api_user: "{{ pve_monica_api_user }}"
      #   api_token_id: "{{ pve_monica_api_token_id }}"
      #   api_token_secret: "{{ pve_monica_api_token_secret }}"
      #   api_host: "{{ pve_monica_api_host }}"
      #   node: monica
      #   target: monica
      #   name: Docker_Host
      #   description: Docker Host

      #   agent: true
      #   autostart: true

      #   # Memory
      #   balloon: 0
      #   memory: 4096
      #   cores: 4
      #   # cpu: x86-64-v2-AES

      #   storage: Speedy

      #   clone: ubuntu-cloud
      #   newid: 133
      #   # vmid: 9000

      #   timeout: 360
      #   state: present
      # register: result
      notify: Cloud-Init Config

  handlers:

    - name: Cloud-Init Config
      ansible.builtin.shell:
        chdir: /home/{{ ansible_user }}
        cmd: |
            sudo qm set 133 --ipconfig0 ip=192.168.1.33/24,gw=192.168.1.1
      changed_when: true
      listen: Create new vm with minimal options

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ result }}"
      listen: Create new vm with minimal options
