---
- name: Update apt package index
  ansible.builtin.apt:
    update_cache: true

- name: Upgrade all packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    autoremove: true

- name: Check if reboot is needed
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot if required
  ansible.builtin.reboot:
  when: reboot_required.stat.exists