- hosts: monica
  become: false
  gather_facts: false
  tasks:

  - name: Create new vm with minimal options
    vars:
      ansible_python_interpreter: /usr/bin/python3
    vars_files:
      - secrets.yml
    proxmox_kvm:
      api_user: "{{ pve_monica_api_user }}"
      api_token_id: "{{ pve_monica_api_token_id }}"
      api_token_secret: "{{ pve_monica_api_token_secret }}"
      api_host: "{{ pve_monica_api_host }}"
      node: monica
      name: vmtest