- hosts: windows_test
  remote_user: matthew
  gather_facts: true

  tasks:
  - name: set the default shell to PowerShell
    win_regedit:
      path: HKLM:\SOFTWARE\OpenSSH
      name: DefaultShell
      data: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
      type: string
      state: present
