- hosts: windows
  remote_user: matthew
  gather_facts: false

  tasks:
  - name: Install PSWindowsUpdate if not installed
    win_chocolatey:
      name: PSWindowsUpdate
      state: latest

  - name: Install all updates and reboot as many times as needed
    ansible.windows.win_updates:
      category_names: ["Application","Connectors","CriticalUpdates","DefinitionUpdates","DeveloperKits","FeaturePacks","Guidance","SecurityUpdates","ServicePacks","Tools","UpdateRollups","Updates","Upgrades"]
      reboot: true
      reboot_timeout: 10000
