- name: Create user defined bridge network
  docker_network:
    name: bridge_01
    driver: bridge
    ipam_config:
      - subnet: 192.168.1.0/24
        gateway:  192.168.1.1
        iprange:  192.168.1.0/24

# - name: Create macvlan network
#   docker_network:
#     name: macvlan_01
#     driver: macvlan