# ansible-playbook -i inventory/inventory.yml playbooks/docker_setup.yml

---
- name: Install Docker
  hosts: docker_host
  become: true
  roles:
    - docker
  vars_files:
    - /root/ansible/group_vars/secrets.yml
    - /root/ansible/roles/docker/vars/main.yml
