- name: install latest qemu-guest-agent
  hosts: "ubuntu"
  tasks:
    - name: install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
        update_cache: true
      become: true
    - name: Start QEMU Guest Agent
      ansible.builtin.systemd:
        state: started
        name: qemu-guest-agent
      become: true
