version: "3"

# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # networks:
    #   bridge_02:
    #     ipv4_address:  192.168.1.9
    # network_mode: "host" 
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "5353:53/tcp"
      - "5353:53/udp"
      # - "6767:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "8080:80/tcp"
    environment:
      TZ: 'America/Phoenix'
      WEBPASSWORD: 'admin'
    
    # Volumes store your data between container upgrades
    volumes:
      - /server/containers/pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped # Recommended but not required (DHCP needs NET_ADMIN)
 
# networks:
#   bridge_02:
#     driver: bridge
#     ipam:
#       # name: bridge_02
#       config:
#         - 
#           subnet:  192.168.1.0/24
#           # gateway:  192.168.1.1
#           # ip_range:  192.168.1.9/32
#     # external: true